// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertInbox = `-- name: InsertInbox :execrows
INSERT INTO inbox (update_id, task_id)
VALUES ($1, $2)
ON CONFLICT (update_id) DO NOTHING
`

type InsertInboxParams struct {
	UpdateID uuid.UUID
	TaskID   uuid.UUID
}

// Records a processed worker update. update_id is the idempotency key: 0 rows
// affected means this update was already processed (a duplicate delivery).
// A concurrent insert of the same id waits on the first one's unique-index
// entry, then sees it once the first commits (DESIGN.md §5).
func (q *Queries) InsertInbox(ctx context.Context, arg InsertInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInbox, arg.UpdateID, arg.TaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
