// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type Inbox struct {
	UpdateID   uuid.UUID
	TaskID     uuid.UUID
	ReceivedAt time.Time
}

type Outbox struct {
	ID          int64
	TaskID      uuid.UUID
	RoutingKey  string
	Payload     []byte
	CreatedAt   time.Time
	PublishedAt *time.Time
}

type Task struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Type      string
	Status    string
	Error     *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	Status    string
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
