// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (task_id, routing_key, payload)
VALUES ($1, $2, $3)
`

type InsertOutboxParams struct {
	TaskID     uuid.UUID
	RoutingKey string
	Payload    []byte
}

// Written in the same tx as the tenant and task (DESIGN.md §6). The relay's
// queries are added with the relay (PLAN.md 4.2).
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.TaskID, arg.RoutingKey, arg.Payload)
	return err
}
