// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getTask = `-- name: GetTask :one
SELECT id, tenant_id, type, status, error, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (tenant_id, type, status)
VALUES ($1, $2, 'accepted')
RETURNING id, tenant_id, type, status, error, created_at, updated_at
`

type InsertTaskParams struct {
	TenantID uuid.UUID
	Type     string
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask, arg.TenantID, arg.Type)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, tenant_id, type, status, error, created_at, updated_at FROM tasks
WHERE ($1::uuid IS NULL OR tenant_id = $1::uuid)
  AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3
`

type ListTasksParams struct {
	TenantID  *uuid.UUID
	Cursor    *uuid.UUID
	PageLimit int32
}

// Keyset pagination, newest first, optionally for one tenant (DESIGN.md §7).
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.TenantID, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTask = `-- name: LockTask :one
SELECT id, tenant_id, type, status, error, created_at, updated_at FROM tasks
WHERE id = $1
FOR NO KEY UPDATE
`

// Serializes updates to one task (DESIGN.md §5). NO KEY UPDATE, not UPDATE:
// the key never changes, so foreign-key checks against the row aren't blocked.
func (q *Queries) LockTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, lockTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
   SET status = $2, error = $3, updated_at = now()
 WHERE id = $1
RETURNING id, tenant_id, type, status, error, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID
	Status string
	Error  *string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status, arg.Error)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
