// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const applyTenantOutcome = `-- name: ApplyTenantOutcome :one
UPDATE tenants
   SET status = $1, version = version + 1, updated_at = now()
 WHERE id = $2 AND status = $3
RETURNING id, slug, name, status, version, created_at, updated_at
`

type ApplyTenantOutcomeParams struct {
	NextStatus     string
	ID             uuid.UUID
	ExpectedStatus string
}

// A terminal task outcome moves its tenant (DESIGN.md §4), guarded on the
// status the tenant must be in. No row means that invariant is broken.
func (q *Queries) ApplyTenantOutcome(ctx context.Context, arg ApplyTenantOutcomeParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, applyTenantOutcome, arg.NextStatus, arg.ID, arg.ExpectedStatus)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, slug, name, status, version, created_at, updated_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTenant = `-- name: InsertTenant :one
INSERT INTO tenants (slug, name, status)
VALUES ($1, $2, 'provisioning')
RETURNING id, slug, name, status, version, created_at, updated_at
`

type InsertTenantParams struct {
	Slug string
	Name string
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, insertTenant, arg.Slug, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, name, status, version, created_at, updated_at FROM tenants
WHERE $1::uuid IS NULL OR id < $1::uuid
ORDER BY id DESC
LIMIT $2
`

type ListTenantsParams struct {
	Cursor    *uuid.UUID
	PageLimit int32
}

// Keyset pagination, newest first (DESIGN.md §7). A NULL cursor starts at the top.
func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTenantDestroying = `-- name: MarkTenantDestroying :one
UPDATE tenants
   SET status = 'destroying', version = version + 1, updated_at = now()
 WHERE id = $1 AND status IN ('active', 'failed')
RETURNING id, slug, name, status, version, created_at, updated_at
`

// The DELETE guard: status only, no version (DESIGN.md §5).
func (q *Queries) MarkTenantDestroying(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, markTenantDestroying, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantIfActive = `-- name: UpdateTenantIfActive :one
UPDATE tenants
   SET name = $2, status = 'updating', version = version + 1, updated_at = now()
 WHERE id = $1 AND status = 'active' AND version = $3
RETURNING id, slug, name, status, version, created_at, updated_at
`

type UpdateTenantIfActiveParams struct {
	ID              uuid.UUID
	Name            string
	ExpectedVersion int32
}

// The PATCH guard (DESIGN.md §5): one conditional UPDATE, no read-then-write.
// No row returned (pgx.ErrNoRows) means the guard didn't match.
func (q *Queries) UpdateTenantIfActive(ctx context.Context, arg UpdateTenantIfActiveParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantIfActive, arg.ID, arg.Name, arg.ExpectedVersion)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
